export const appImages = {
    report: require('../../../assets/images/icons/report.png'),
    businessCard: require('../../../assets/images/icons/business-card.png'),
    calendar: require('../../../assets/images/icons/calendar.png'),
    calendarRejection: require('../../../assets/images/icons/calendar-rejection.png'),
    carBooking: require('../../../assets/images/icons/vehicle.png'),
    carLoan: require('../../../assets/images/icons/car-loan.png'),
    catering: require('../../../assets/images/icons/catering.png'),
    certificateRequest: require('../../../assets/images/icons/certificate-request.png'),
    completedRequest: require('../../../assets/images/icons/completed.png'),
    draft: require('../../../assets/images/icons/draft.png'),
    education: require('../../../assets/images/icons/education.png'),
    employee: require('../../../assets/images/icons/employee.png'),
    houseLoan: require('../../../assets/images/icons/house-loan.png'),
    hse: require('../../../assets/images/icons/hse.png'),
    ibtikar: require('../../../assets/images/icons/ibtikar.png'),
    incident: require('../../../assets/images/icons/report-incident.png'),
    kpi: require('../../../assets/images/icons/kpi.png'),
    manager: require('../../../assets/images/icons/manager.png'),
    meetingRoom: require('../../../assets/images/icons/meeting-room.png'),
    missingAttendance: require('../../../assets/images/icons/reports.png'),
    payslip: require('../../../assets/images/icons/payslip.png'),
    pendingRequest: require('../../../assets/images/icons/progress.png'),
    remoteWork: require('../../../assets/images/icons/cloud.png'),
    reportees: require('../../../assets/images/icons/team.png'),
    salaryAdvanced: require('../../../assets/images/icons/salary-loan.png'),
    skillsBank: require('../../../assets/images/icons/person-report.png'),
    teamLeaves: require('../../../assets/images/icons/team-leaves.png'),
    violation: require('../../../assets/images/icons/team-violation.png'),
    azure: require('../../../assets/images/azure-logo.png'),
    logo: require('../../../assets/images/employeeGateway-logo.png'),
    splash: require('../../../assets/images/bg/splash.png'),
    bg: require('../../../assets/images/bg/bg.png'),
    adportsLogo: require('../../../assets/images/adports-logo.png'),
    illustration:require('../../../assets/images/illustration.png'),
    illustrationbg:require('../../../assets/images/illustration-2.png'),
    verticalLogo:require('../../../assets/images/vertical-logo.png'),
    plane:require('../../../assets/images/icons/business-trip.png'),
    sun:require('../../../assets/images/sun.png'),
    hand:require('../../../assets/images/hand.png'),
    boat:require('../../../assets/images/icons/boat-calendar.png'),
    teamSuggestions:require('../../../assets/images/icons/team-suggestions.png'),
    login:require('../../../assets/images/icons/login.png'),
    logout:require('../../../assets/images/icons/logout.png'),
    vacation:require('../../../assets/images/icons/vacation.png'),
    timein:require('../../../assets/images/icons/clock.png'),
    absense:require('../../../assets/images/icons/absense.png'),
    location:require('../../../assets/images/icons/location.png'),
    sickLeave:require('../../../assets/images/icons/sick-leave.png'),
    annualLeave:require('../../../assets/images/icons/annual-leave.png'),
    fabs:require('../../../assets/images/fabs.png'),
}